name: "release-v6-dind"
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch'
        required: true
        default: 'V6.0'
      version:
        description: 'version'
        required: true
        default: 'v6.0.0-release'
      platforms:
        description: 'platforms'
        required: true
        default: 'linux/amd64'
        type: choice
        options:
          - linux/amd64
          - linux/amd64,linux/arm64
      
env:
  VERSION: ${{ github.event.inputs.version }}
  
jobs:
  rainbond-allinone:
    runs-on: ubuntu-latest
    environment: release-v6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: goodrain/rainbond-console
          ref: ${{ github.event.inputs.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          password: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}
      
      - name: Pull Docker image
        run: |
          VERSION=${{ env.VERSION }} cd standalone && sh ./images-package.sh
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ github.event.inputs.platforms }}
          build-args: |
            VERSION=${{ env.VERSION }}
          context: standalone
          file: ./Dockerfile
          push: true
          tags: |
            rainbond/rainbond:${{ env.VERSION }}-dind
            registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:${{ env.VERSION }}-dind
